export const countryNameMap = {
  AND: 'Andorra',
  ARG: 'Argentina',
  AUS: 'Australia',
  BGD: 'Bangladesh',
  ARM: 'Armenia',
  BOL: 'Bolivia',
  BRA: 'Brazil',
  MMR: 'Myanmar',
  CAN: 'Canada',
  CHL: 'Chile',
  CHN: 'China',
  DEU: 'Germany',
  TWN: 'Taiwan',
  COL: 'Colombia',
  CYP: 'Cyprus',
  CZE: 'Czechia',
  ECU: 'Ecuador',
  ETH: 'Ethiopia',
  GRC: 'Greece',
  GTM: 'Guatemala',
  HKG: 'Hong Kong',
  IND: 'India',
  IDN: 'Indonesia',
  IRN: 'Iran',
  IRQ: 'Iraq',
  JOR: 'Jordan',
  JPN: 'Japan',
  KAZ: 'Kazakhstan',
  KEN: 'Kenya',
  KOR: 'South Korea',
  KGZ: 'Kyrgyzstan',
  LBN: 'Lebanon',
  LBY: 'Libya',
  MAC: 'Macao',
  MYS: 'Malaysia',
  MDV: 'Maldives',
  MEX: 'Mexico',
  MNG: 'Mongolia',
  MOR: 'Morocco',
  NLD: 'Netherlands',
  NIC: 'Nicaragua',
  NGA: 'Nigeria',
  NZL: 'New Zealand',
  PAK: 'Pakistan',
  PER: 'Peru',
  PHL: 'Philippines',
  PRI: 'Puerto Rico',
  ROU: 'Romania',
  RUS: 'Russia',
  SRB: 'Serbia',
  SGP: 'Singapore',
  SVK: 'Slovakia',
  TUR: 'Turkey',
  VNM: 'Vietnam',
  ZWE: 'Zimbabwe',
  TJK: 'Tajikistan',
  THA: 'Thailand',
  TUN: 'Tunisia',
  UKR: 'Ukraine',
  EGY: 'Egypt',
  GBR: 'United Kingdom',
  USA: 'United States',
  URY: 'Uruguay',
  UZB: 'Uzbekistan',
  VEN: 'Venezuela',
  NIR: 'Northern Ireland'
};
